### ISSUE TITLE
Split the igv.js into modules

### ISSUE THREAD

**Issue by bingbig** [datavisyn/igv_wrapper#2]
Hello, I am wondering if you were trying to split the igv-1.0.9.js into [modules](https://github.com/datavisyn/igv_wrapper/tree/master/lib)? And updating some plugins in igv?

 I'm new to js and I found it's a little confuse to figure out the dependence of igvteam's igv although it's a great bowser.

**Comment by sgratzl** [comment]
Hi, this repository is just using the built version of igv.js. Please take a look at the original repository located at: https://github.com/igvteam/igv.js
